/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `/calificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/detalle-materia`; params?: Router.UnknownInputParams; } | { pathname: `/finales`; params?: Router.UnknownInputParams; } | { pathname: `/horarios`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mis-materias`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/parciales`; params?: Router.UnknownInputParams; } | { pathname: `/plan-estudios`; params?: Router.UnknownInputParams; } | { pathname: `/repositorio`; params?: Router.UnknownInputParams; } | { pathname: `/selectMateria`; params?: Router.UnknownInputParams; } | { pathname: `/simulador`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/herramientas` | `/herramientas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `/calificaciones`; params?: Router.UnknownOutputParams; } | { pathname: `/detalle-materia`; params?: Router.UnknownOutputParams; } | { pathname: `/finales`; params?: Router.UnknownOutputParams; } | { pathname: `/horarios`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mis-materias`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/parciales`; params?: Router.UnknownOutputParams; } | { pathname: `/plan-estudios`; params?: Router.UnknownOutputParams; } | { pathname: `/repositorio`; params?: Router.UnknownOutputParams; } | { pathname: `/selectMateria`; params?: Router.UnknownOutputParams; } | { pathname: `/simulador`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/herramientas` | `/herramientas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/agenda${`?${string}` | `#${string}` | ''}` | `/calificaciones${`?${string}` | `#${string}` | ''}` | `/detalle-materia${`?${string}` | `#${string}` | ''}` | `/finales${`?${string}` | `#${string}` | ''}` | `/horarios${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mis-materias${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/parciales${`?${string}` | `#${string}` | ''}` | `/plan-estudios${`?${string}` | `#${string}` | ''}` | `/repositorio${`?${string}` | `#${string}` | ''}` | `/selectMateria${`?${string}` | `#${string}` | ''}` | `/simulador${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/herramientas${`?${string}` | `#${string}` | ''}` | `/herramientas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/materias${`?${string}` | `#${string}` | ''}` | `/materias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `/calificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/detalle-materia`; params?: Router.UnknownInputParams; } | { pathname: `/finales`; params?: Router.UnknownInputParams; } | { pathname: `/horarios`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mis-materias`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/parciales`; params?: Router.UnknownInputParams; } | { pathname: `/plan-estudios`; params?: Router.UnknownInputParams; } | { pathname: `/repositorio`; params?: Router.UnknownInputParams; } | { pathname: `/selectMateria`; params?: Router.UnknownInputParams; } | { pathname: `/simulador`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/herramientas` | `/herramientas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
    }
  }
}
